# Change these first
owner: Pinelab-studio # Your GitHub organization or username, where this repository lives
repo: upptime2 # The name of this repository

sites:
  - name: HPS
    url: $HPS_SHOP_API
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{ "query": "{ product(id: \"4457\") { id name description slug collections { name id parentId breadcrumbs { slug name } } optionGroups { id code name options { id code name groupId } } featuredAsset { id preview } assets { source name width height } variants { id sku name priceWithTax stockLevel featuredAsset { id preview } assets { source name width height } } facetValues { name id code facet { name id code } } } }" }'
  - name: WKW
    url: $WKW_SHOP_API
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{ "query": "{ product(id: \"4457\") { id name description slug collections { name id parentId breadcrumbs { slug name } } optionGroups { id code name options { id code name groupId } } featuredAsset { id preview } assets { source name width height } variants { id sku name priceWithTax stockLevel featuredAsset { id preview } assets { source name width height } } facetValues { name id code facet { name id code } } } }" }'    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://pinelab.studio/pinelab.svg
  name: Pinelab.studio Upptime
  baseUrl: /upptime2
  introTitle: "Pinelab.studio API monitoring"
  introMessage: "Monitor the status and performance of several API's managed by Pinelab.studio"
  navbar:
    - title: Status
      href: /
    - title: Pinelab.studio
      href: https://pinelab.studio/
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "1 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 2 * * *"
  updateTemplate: "0 3 * * *"
  updates: "0 3 * * *"
  uptime: "* 1 * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
